### ISSUE TITLE
Report Meta on json

### ISSUE THREAD

**Issue by pathumego** [mooniak/Frequency-Counter#13]
- [ ] Number of files analysed
- [x] Number of Words
- [ ] URL's That failed
- [ ] Data count
